### ISSUE TITLE
Create public methods for setting text in header.

### ISSUE THREAD

**Issue by onyxmueller** [erikwt/PullToRefresh-ListView#1]
This is a feature request to create public methods for setting text in header.  More specifically, public methods for changing 'Pull to refresh' and 'Release to refresh' text, to either something else or to nothing at all.

With this being open-source, it was easy enough for me to hack in a solution, but I believe these are good public methods to have.  See the PullToRefreshBase.java file of Chris Banes' project for something similar (https://github.com/chrisbanes/Android-PullToRefresh).

Thanks!

**Comment by erikwt** [comment]
Accepted, will do this in the next update. Thanks for the suggestion!

**Comment by erikwt** [comment]
Fixed with commit 9249e4b
