### ISSUE TITLE
LayoutAnimationController

### ISSUE THREAD

**Issue by Klaasvaak** [erikwt/PullToRefresh-ListView#11]
It is not possible to add a LayoutAnimationController to the PullToRefreshListView.

**Comment by erikwt** [comment]
Could you give a little more detail? I don't understand what you mean...

**Comment by erikwt** [comment]
I tested this, and yes you can add a LayoutAnimationController to PullToRefreshListView in the same way as you would add one to a normal ListView. The animation works, too ;-)
