### ISSUE TITLE
Android ClassNotFoundException PullToRefreshListView

### ISSUE THREAD

**Issue by narcech** [erikwt/PullToRefresh-ListView#12]
I add the PullToRefreshListView.java source code into my package, the app runs well before I packaged it with progard.cfg, but it went wrong after that operation
And it throw ClassNotFoundException Error.

07-19 15:09:14.776: E/AndroidRuntime(585): Caused by: java.lang.ClassNotFoundException: com.xx.xxx.widget.PullToRefreshListView

this happended after I update my ADT(this ADT can send warn infos in the XML file). it goes well before I update this ADT.
And I tried to update the Android SDK too, still not working.

and I add this PullToRefreshListView widget in the XML file like this:

```
    <com.xx.xxx.widget.PullToRefreshListView
        android:id="@+id/contentFlowList"
        style="@style/pull_refresh_listview_style"
        android:listSelector="@android:color/transparent" >
    </com.xx.xxx.widget.PullToRefreshListView>
```

the ADT version20.0.1's requirement is here. And I checked nothing's wrong with the environment.

I can directly run the App successfully, but crash happends when jump to the Activity containing PullToRefreshListView after I obfuscated code and packaged it.

How can I solve this problem

**Comment by erikwt** [comment]
Is there a reason you don't use this project as a library? You need to tell proguard to not obfuscate the PullToRefreshListView class by adding this to your proguard config file:

-keep public class com.xx.xxx.widget.PullToRefreshListView
