### ISSUE TITLE
Refresh incorrectly triggers when doing a continuous long touch

### ISSUE THREAD

**Issue by madisp** [erikwt/PullToRefresh-ListView#15]
## Reproduction
1. Start by pulling the listview to refresh, the header changes state to "Release to refresh"
2. Instead of letting go of the finger scroll back down and start scrolling up again

**Expected result:**

The list is not refreshed

**Actual result:**

The list is locked, refreshing commences

**Comment by erikwt** [comment]
Fixed by madisp. Thanks.
