### ISSUE TITLE
Adding layout animation does not work.

### ISSUE THREAD

**Issue by onyxmueller** [erikwt/PullToRefresh-ListView#2]
There seems to be an issue when adding a layout animation set to PullToRefreshListView via ListView's setLayoutAnimation.  The animations being set do not work/run.

I haven't tested this issue extensively, but I did have working code that used a ListView and would run a simple animation when an item was added to the list.  When I swapped the ListView for a PullToRefreshListView, the animation would no longer run.

**Comment by erikwt** [comment]
Will look into this. Do you have some example code? Like the animation that you are using that doesn't work?

**Comment by onyxmueller** [comment]
Here's a snippet of the animation code being applied to the ListView/PullToRefreshListView:

https://gist.github.com/3cc77d8c00fd070aff24

When applying the layout animation to a ListView it works...but not with PullToRefreshListView.

**Comment by erikwt** [comment]
Accepted, I'll fix this.

**Comment by erikwt** [comment]
I added your gist code to the sample project in a branch (layoutanim branch, see above comment). It works flawlessly for me. Can you test if it works for you as well by checking out the layoutanim branch and running it?
