### ISSUE TITLE
setRefreshing does not work inside a Async Task

### ISSUE THREAD

**Issue by schilakamarri** [erikwt/PullToRefresh-ListView#20]

**Comment by erikwt** [comment]
You should do this on the UI thread. You can use runOnUiThread(..) or View.Post(..) or similar.

**Comment by schilakamarri** [comment]
Hi Erik, I could not get it to work at all. I have a async task that I start as follows in my OnCreate Method in my activity:

new RefreshTask().execute.

It has OnPreExecute(), DoInBackground() and OnPostExecute() methods.

Where do you think I should include listView.setRefreshing()? Can you give an example?

Thank you!

**Comment by erikwt** [comment]
I suppose you should do that call in onPostExecute(..). Can you post the code that doesn't work for you? Maybe in a gist?

**Comment by schilakamarri** [comment]
It does not work when I place listView.setRefreshing() in onPostExecute() method.

I run a asynctask from onCreate() method as:

public void onCreate(Bundle savedInstanceState) {
        pull_listView = (PullToRefreshListView) app.findViewById(R.id.pull_to_refresh_listview);
        pull_listView.setShowLastUpdatedText(true);
        pull_listView.setLastUpdatedDateFormat(new SimpleDateFormat("yyyy/MM/dd HH:mm:ss"));
        pull_listView.setTextPullToRefresh("Pull to Refresh");
        pull_listView.setTextReleaseToRefresh("Release to Refresh");
        pull_listView.setTextRefreshing("Refreshing..");
        MyAsycTask.execute();
...
...
}

And then:

```
private class MyAyncTask extends AsyncTask<Void, Void, String[]> {

     protected void onPreExecute() {

     }
     protected String[] doInBackground(Void... params) {
           //some HTTP calls made
      }

     protected void onPostExecute(String[] result) {
       // a  pull_listView is populated 
        pull_listView.onRefreshComplete();
     }

}
```

**Comment by erikwt** [comment]
Ah, the setRefreshing() should be called in onPreExecute(), then onRefreshComplete() in onPostExecute(). Does that work for you? Also, be sure to check the sample project for the exact function calls.

**Comment by miao1007** [comment]
Thanks ! It works fine on my fragment :+1:
