### ISSUE TITLE
onRefresh() is not called when I force it with setRefreshing()

### ISSUE THREAD

**Issue by alebrot** [erikwt/PullToRefresh-ListView#21]
I assume that it should be called but instead only the progress bar continues spinning.
It seems you have a bug in the method   

public void setRefreshing(){
        state = State.REFRESHING;
        scrollTo(0, 0);
        setUiRefreshing();
        setHeaderPadding(0);

```
}
```

This method should be changed to:

public void setRefreshing(){
        setState(State.REFRESHING);
        scrollTo(0, 0);
        setUiRefreshing();
        setHeaderPadding(0);

```
}
```

By setting the state this way the  onRefreshListener.onRefresh(); is called.

**Comment by erikwt** [comment]
Actually, setRefreshing(..) is supposed to only be an UI action. The use case for this is, for example, on application start. The service has already begun loading (manually) and the UI needs to be updated accordingly.

**Comment by alebrot** [comment]
Thank you for the response, It would be nice to have a method that forces calling onRefresh().
Let's say setRefreshing() for UI  and refresh() for real refreshing that includes UI refreshing as well.

**Comment by erikwt** [comment]
Thanks for your feedback, if there is more demand for this I will add it soon. Cheers!
