### ISSUE TITLE
Each time I pull to refresh my item in the list is clicked

### ISSUE THREAD

**Issue by lechon** [erikwt/PullToRefresh-ListView#25]
Hi, 
I'm trying to use your project but actually I'm having a problem with the ClickEvent. 
Each time I do pull to refresh, the item pressed under my finger is called with the ClickEvent. I need to be able to do click the items but not when i'm refreshing it. 
I've been trying to control the list onItemClick event with the  method isRefreshing() but before the State is updated, the Item Click Event is called and launch the detail associated to this item.
Is there any way to control the pass of the event? 

Ps: when I declare the  < eu.erikw.PullToRefreshListView..  I've added the  android:clickable="false"/>.

**Comment by erikwt** [comment]
Hi, are you using the master or development branch? And are you up to date?

Erik

**Comment by lechon** [comment]
I have the master branch and yes, i download the latest version two weeks ago. 
Jose M

**Comment by erikwt** [comment]
Could you try the 'development' branch? There are some fixes merged there from pull requests that might solve your problem.

Erik

**Comment by lechon** [comment]
Thanks, I will try asap.
Jose M

**Comment by wemakeweb** [comment]
I have the same Issue with the development branch. Seams to happen  if you pull the menu down very fast

**Comment by lechon** [comment]
Yes, the problem has been kept in both branches. There's a few better things in the developer branch but this problem hasn't been solved yet. Totally agree with wemakeweb, if you click carefully, you might avoid select a row, but this way it isn't easy to use when we have to use both effects, pull and click.

**Comment by erikwt** [comment]
Fix merged in master and development. Thanks @vibu!
