### ISSUE TITLE
Flicker when setAdapter

### ISSUE THREAD

**Issue by Joohansson** [erikwt/PullToRefresh-ListView#27]
When re-loading the listView in the code (listView.setAdapter(adapter)), the header with the text "Pull to refresh" and the arrow is shown for a fraction of a second every time. Maybe it´s not possible to solve?

A solution is to define adapter globally and do the listView.setAdapter(adapter) one time only on onCreate. Then only do adapter.loadData() to update the view. Maybe that is the intended way to code..

**Comment by erikwt** [comment]
Yes, you shouldn't set the adapter every time. Use notifydatasetchanged() in the Adapter instead.
