### ISSUE TITLE
animation "stutters" if listview has padding

### ISSUE THREAD

**Issue by andaag** [erikwt/PullToRefresh-ListView#29]
This fixes the issue:
https://github.com/finn-no/PullToRefresh-ListView/commit/e80c02ccbe3e005714b157b3966d31c78e30d041

**Comment by erikwt** [comment]
Thanks, can you make a pull request so I can auto-merge the change?

Erik

**Comment by andaag** [comment]
Sorry about the delay on this, it was on my todo list and drowned slightly. (We got a release due on friday ;) ).

https://github.com/erikwt/PullToRefresh-ListView/pull/32

**Comment by erikwt** [comment]
No worries, thanks!
