### ISSUE TITLE
listview items not completely displayed

### ISSUE THREAD

**Issue by jom16antonio** [erikwt/PullToRefresh-ListView#3]
I am using a listview that partially occupies the screen. Now when my items exceed the rows shown by default, the last item when finger scrolled down is only shown half and not the full cell row.

**Comment by erikwt** [comment]
I'm looking into it, thanks for letting me know!

**Comment by jom16antonio** [comment]
nvm, it was a bug in my layout that uses relativelayout. It was not able to account for the height of the status bar, therefore having the last cell overlap the screen. This makes it display half only of the cell. the pull to refresh listview has no such issue. thanks for addressing my concern.

**Comment by kimziv** [comment]
has the same problem , it is not fixed ....
