### ISSUE TITLE
InflateException: Binary XML file

### ISSUE THREAD

**Issue by AlexAndro1** [erikwt/PullToRefresh-ListView#8]
I have added the jar from libraryproject\bin, to my project, I was able to access the class in .java classes but in the .xml file I get InflateException on "<eu.erikw.PullToRefreshListView" , "Caused by: java.lang.ClassNotFoundException: eu.erikw.PullToRefreshListView" .
Please tell me how to solve this issue.

I solved it, but I had to copy the files from library in project....

**Comment by erikwt** [comment]
You should import the whole libraryproject in your IDE and configure your project to use the PullToRefreshListView libraryproject as a library. This way, you don't have to copy anything. :)
